theme: minima
title: Learning Pages Blog
author: theChad
email: theChad@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Does it also ignore tabs here? So I'll put in a newline here:
  and does it tab in the description? Also, just for indexing fun,
  I'll write 3/17/21 14:53 bh780utihbchxfhgh

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
